### ISSUE TITLE
Running with ionic package & Windows?

### ISSUE THREAD

**Issue by Lyricalz** [driftyco/cordova-plugin-wkwebview-engine#31]
Hey i've heard great things about this plugin and what it does for performance and want to test it out myself!

I was wondering for someone like me (developing on a windows with no xcode access) how would I install this plugin? [Instructions](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions)  kind of suggest a solution for mac developers, but not windows?

I've been using ionic package to build for ios btw

**Comment by jgw96** [comment]
Hello @Lyricalz , have you tried installing the plugin and then building it with ionic package? It should just work like installing any other plugin.

**Comment by Lyricalz** [comment]
@jgw96 assuming i'm installing correctly.. I already had android & ios platforms added

Then I did 

`ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save`

Basically got:

Plugin "cordova-plugin-wkwebview-engine" already installed on android.


Installing "cordova-plugin-wkwebview-engine" for ios


cordova-ios version check failed (".....platforms\ios\cordova\version"), continuing anyways.


apple-ios version check failed (".....platforms\ios\cordova\apple_ios_version"), continuing anyways.


 Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.

Failed to install 'cordova-plugin-wkwebview-engine':Error: ENOENT: no such file or directory, open '.....platforms\ios\CordovaLib\VERSION'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports.parseProjectFile (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\ios.js:283:33)
    at PlatformApiPoly.addPlugin (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:242:71)
    at handleInstall (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:611:6)
    at C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:407:28
    at _fulfilled (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Michael\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)


Error: ENOENT: no such file or directory, open 'C:\users\michael\dropbox\wamp\www\ionicfr\platforms\ios\CordovaLib\VERSION'


Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Which I guess makes sense to me in a way, since it requires cordova-ios ?

**Comment by Lyricalz** [comment]
@jgw96 ignore this please, it works fine with ionic package. For anyone else, just install the plugin as this repo instructs and ignore everything else.

`ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save`

then build with package, this really does improve performance ALOT.
